name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      # Checkout Repository.
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup CCache
        uses: hendrikmuhs/ccache-action@v1.2

      # Install Tools.
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget build-essential ninja-build
          sudo apt-get install -y libevent-dev libjson-c-dev flex bison
          sudo apt-get install -y libfl-dev libfl2 zlib1g-dev

      # Install Python.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: "setup.py"

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install setuptools requests pexpect meson pytest

      # Install Migen / LiteX / Cores.
      - name: Install LiteX
        run: |
          mkdir -p third_party
          cd third_party
          wget https://raw.githubusercontent.com/enjoy-digital/litex/master/litex_setup.py
          python3 litex_setup.py --config=standard --init --install --user

      # Build / Install Verilator.
      - name: Build Verilator
        run: |
          sudo apt-get install help2man
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          git clone https://github.com/verilator/verilator
          cd verilator
          git checkout 7d2d32420a630befa4097170ecbf227e04e32522
          autoconf
          ./configure
          make -j$(nproc)
          sudo make install

      # Install Project.
      - name: Install Project
        run: python3 setup.py develop --user

      # Test.
      - name: Run Tests
        run: |
          python3 -m pytest -v test
